### PR TITLE
don't download if model file if provided

### LINKED ISSUE #21: Unable to download model to EMR, fix if params and checkpoint provided, avoid redownload
The EMR needs model files to be downloaded to `/tmp` and default home `/var/lib/livy` is inaccessible to users.

So, I managed to download the content separately in my case, but even passing weights path in parameters didn't work

### PR DESCRIPTION
**Pull request by Nempickaxe**
fixes #21

### CODE REVIEW

**Comment by harikodali** [comment]
hi, thanks for spotting it, make changes to check for both paths individually

**Comment by Nempickaxe** [comment]
Sure, will make the changes

**Comment by Nempickaxe** [comment]
@harikodali can you check and merge?

**Comment by bedapudi6788** [comment]
@Nempickaxe looks good!

**Pull request merged**
